### ISSUE TITLE
How to set sidebar?

### ISSUE THREAD

**Issue by ylqi007** [rundocs/rundocs.io#1]
There have four top levels in the left side bar in this [page](https://rundocs.io/configuring/sidebar.html), i.e. Installation, Configuration, Writing related and Contributing. And there has four folders corresponding to these four top levels under `docs/`. I set like the same way, but there is now top levels like the demo page. Could you please write some doc to show how to set top level sidebar?

Sincerely,

**Comment by saowang** [comment]
The definition is this: the first level folder is used as the chapter folder. It should be noted that any folder, including chapters, must have an index, that is, readme, to be displayed in the sidebar.
